accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path('', views.index, name="accounts"),
    path('login/', views.login, name="login"),
    path('register/', views.register, name="register"),
    path('logout/', views.logout, name="logout"),
]

dashboard/urls.py
from django.urls import path
from . import views


app_name = "dashboard"
urlpatterns = [
    path('', views.dashboard, name='dashboard')
]

home/urls.py
from django.urls import path

from . import views

app_name = "home"
urlpatterns = [
    path('', views.FindAHomeListView.as_view(), name='homes'),
]

owners/urls.py
from django.conf.urls import url
from . import views

app_name = "owners"
urlpatterns = [
    url('^$', views.owners, name="owners"),
    url(r'^(?P<id>\d+)/create-review/$', views.create_review, name="create_review"),
    url(r'^(?P<pk>\d+)/$', views.owner_detail, name='profile'),
]

pages/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = "pages"
urlpatterns = [
    path('', views.index, name="home"),
    url(r'^(?P<pk>\d+)/$', views.HomePageDetailsView.as_view(), name='detail'),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
    path('faq/', views.faq, name='faq'),
    path('privacy-policy/', views.privacy, name='privacy'),
    path('terms-of-agreement/', views.terms, name='terms'),
]

rental_program/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('pages.urls', namespace='pages')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('home/', include('home.urls', namespace='home')),
    path('renters/', include('renters.urls', namespace='renters')),
    path('owners/', include('owners.urls', namespace='owners')),
    path('properties/', include('properties.urls', namespace='properties')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/_partials/_alerts.html
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container">
            <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
                <strong>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        Error:
                    {% else %}
                        {{ message.tags | title }}
                    {% endif %}
                </strong>
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}

templates/_partials/_footer.html
{% load static %}
<footer class="footer footer-default">
    <div class="container">
      <nav class="float-left">
        <ul>
          <li>
            <a class="nav-link" href="{% url 'pages:home' %}">Home</a>
          </li>
          <li>
            <a href="https://creative-tim.com/presentation">
              About Us
            </a>
          </li>
          <li>
            <a href="http://blog.creative-tim.com">
              Blog
            </a>
          </li>
          <li>
            <a href="https://www.creative-tim.com/license">
              Licenses
            </a>
          </li>
        </ul>
      </nav>
      <div class="copyright float-right">
        &copy;
        <script>
          document.write(new Date().getFullYear())
        </script> by
        <a href="#" target="_blank">Kevin Stradtman</a>
      </div>
    </div>
  </footer>

templates/_partials/_navbar.html
{% load static %}
<nav class="navbar navbar-color-on-scroll navbar-transparent    fixed-top  navbar-expand-lg " color-on-scroll="100" id="sectionsNav">
    <div class="container">
      <div class="navbar-translate">
        <a class="navbar-brand" href="{% url 'pages:home' %}">
          Welcome Home {{ user.username }}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="sr-only">Toggle navigation</span>
          <span class="navbar-toggler-icon"></span>
          <span class="navbar-toggler-icon"></span>
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
        <ul class="navbar-nav ml-auto">

            <li class="dropdown nav-item">
                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                    <i class="material-icons">home</i> Home
                </a>
                <div class="dropdown-menu dropdown-with-icons">
                    <a href="{% url 'pages:home' %}" class="dropdown-item">
                        <i class="material-icons">home</i> Main Page
                    </a>
                </div>
            </li>

            <li class="dropdown nav-item">
                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                    <i class="material-icons">search</i> Find A Home
                </a>
                <div class="dropdown-menu dropdown-with-icons">
                    <a href="{% url 'home:homes' %}" class="dropdown-item">
                        <i class="material-icons">home</i> Home
                    </a>
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'owners:owners' %}" class="dropdown-item">
                            <i class="material-icons">account_circle</i> Owners
                        </a>
                        <a href="{% url 'properties:add_property' %}" class="dropdown-item">
                            <i class="material-icons">add</i> Add Property
                        </a>
                    {% endif %}
                </div>
            </li>

            {% if request.user.is_authenticated %}

                <li class="dropdown nav-item">
                    <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                        <i class="material-icons">assessment</i> Dashboard
                    </a>
                    <div class="dropdown-menu dropdown-with-icons">
                        <a href="{% url 'dashboard:dashboard' %}" class="dropdown-item">
                            <i class="material-icons">home</i> Dashboard Home
                        </a>
                    </div>
                </li>

            {% endif %}

            <li class="dropdown nav-item">
                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                    <i class="material-icons">manage_accounts</i> Account
                </a>
                <div class="dropdown-menu dropdown-with-icons">
                    {% if user.is_authenticated %}
                        <a href="{% url 'accounts:logout' %}" class="dropdown-item">
                            <i class="material-icons">logout</i> Log Out
                        </a>
                    {% else %}
                        <a href="{% url 'accounts:login' %}" class="dropdown-item">
                            <i class="material-icons">login</i> Login
                        </a>
                        <a href="{% url 'accounts:register' %}" class="dropdown-item">
                            <i class="material-icons">add</i> Register
                        </a>
                    {% endif %}
                    <a href="#" class="dropdown-item">
                        <i class="material-icons">settings</i> Settings
                    </a>
                </div>
            </li>

            <li class="dropdown nav-item">
                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                    <i class="material-icons">fact_check</i> FAQ
                </a>
                <div class="dropdown-menu dropdown-with-icons">
                    <a href="{% url 'pages:about' %}" class="dropdown-item">
                        <i class="material-icons">account_circle</i> About Us
                    </a>
                    <a href="{% url 'pages:privacy' %}" class="dropdown-item">
                        <i class="material-icons">privacy_tip</i> Privacy Policy
                    </a>
                    <a href="{% url 'pages:terms' %}" class="dropdown-item">
                        <i class="material-icons">ballot</i> Terms of Agreement
                    </a>
                    <a href="{% url 'pages:faq' %}" class="dropdown-item">
                        <i class="material-icons">fact_check</i> FAQ
                    </a>
                    <a href="{% url 'pages:contact' %}" class="dropdown-item">
                        <i class="material-icons">create</i> Contact
                    </a>
                </div>
            </li>

        </ul>
    </div>
  </nav>