contacts/urls.py
from django.conf.urls import url
from . import views

app_name = "contacts"

urlpatterns = [
    url('^$', views.index, name="contacts"),
]

home/urls.py
from django.urls import path

from . import views

app_name = "home"
urlpatterns = [
    path('', views.FindAHomeListView.as_view(), name='homes'),
]

pages/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = "pages"
urlpatterns = [
    path('', views.index, name="home"),
    url(r'^(?P<pk>\d+)/$', views.HomePageDetailsView.as_view(), name='detail'),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
    path('faq/', views.faq, name='faq'),
    path('privacy-policy/', views.privacy, name='privacy'),
    path('terms-of-agreement/', views.terms, name='terms'),
]

rental_program/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('pages.urls', namespace='pages')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('home/', include('home.urls', namespace='home')),
    path('renters/', include('renters.urls', namespace='renters')),
    path('owners/', include('owners.urls', namespace='owners')),
    path('properties/', include('properties.urls', namespace='properties')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts/models.py
from django.db import models

# Create your models here.

contacts/views.py
from django.shortcuts import render
from . import models
from owners.models import Owner

def index(request):
    context = {}
    return render(request, 'contacts/contacts.html', context)

templates/pages/about.html
{% extends 'base.html' %}
{% block title %} {{ super }} | About the Rentals App {% endblock %}
{% block content %}

{% endblock %}

templates/pages/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ super }} | Contact the Rentals App {% endblock %}
{% block content %}

    <div class="page-header header-filter" data-parallax="true" style="background-image: url('{% static "kit/assets/img/bg8.jpg"%}')">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h1 class="title">Contact Us</h1>
                    <h4>Contact us via email, telephone or from the contact form that is below</h4>
                </div>
            </div>
        </div>
    </div>
     <div class="main main-raised">
        <div class="container">
            <div class="section text-center">
                <div class="row">
                    <div class="col-md-10 ml-auto mr-auto">
                        <h1 class="text-center mt-3 mb-3">Contact Us</h1>
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input type="text" class="form-control" id="name">
                            </div>
                            <div class="form-group">
                                <label for="email">Email address</label>
                                <input type="email" class="form-control" id="email">
                            </div>
                            <div class="form-group">
                                <label for="subject">Subject</label>
                                <input type="text" class="form-control" id="subject">
                            </div>
                            <div class="form-group">
                                <label for="msg">Message</label>
                                <textarea class="form-control" id="msg" rows="3"></textarea>
                            </div>
                            <input type="submit" class="btn btn-success btn-lg btn-round" value="Submit">
                        </form>
                    </div>
                </div>
            </div>
        </div>
     </div>

{% endblock %}

templates/pages/faq.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ super }} | FAQ - Learn All You Need To Know{% endblock %}
{% block content %}

    <div class="page-header header-filter" data-parallax="true" style="background-image: url('{% static "kit/assets/img/bg8.jpg"%}')">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1 class="title">Facts Answers Questions</h1>
          <h4>Learn more about our company through the pre set facts answers and questions.  You should have everything you need to know on this page.</h4>
        </div>
      </div>
    </div>
  </div>
  <div class="main main-raised">
    <div class="container">
      <div class="section text-center">
        <div class="row">
          <div class="col-md-10 ml-auto mr-auto">
            <div id="accordion" role="tablist" aria-multiselectable="true" class="card-collapse">
                <div class="card card-raised p-1">
                    <div class="card-header" role="tab" id="headingOne">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                            How much does the service cost for a renter?
                            <i class="material-icons">keyboard_arrow_down</i>
                        </a>
                    </div>
                    <div id="collapseOne" class="collapse" role="tabpanel" aria-labelledby="headingOne">
                        <div class="card-body">
                            Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                        </div>
                    </div>
                </div>
                <div class="card card-raised p-1">
                    <div class="card-header" role="tab" id="headingTwo">
                        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                            How much does this service cost for a owner?
                            <i class="material-icons">keyboard_arrow_down</i>
                        </a>
                    </div>
                    <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo">
                        <div class="card-body">
                            Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                        </div>
                    </div>
                </div>
                <div class="card card-raised p-1">
                    <div class="card-header" role="tab" id="headingThree">
                        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                            What type of payment selection do you provide for this service?
                            <i class="material-icons">keyboard_arrow_down</i>
                        </a>
                    </div>
                    <div id="collapseThree" class="collapse" role="tabpanel" aria-labelledby="headingThree">
                        <div class="card-body">
                            Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                        </div>
                    </div>
                </div>
                <div class="card card-raised p-1">
                    <div class="card-header" role="tab" id="headingFour">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                            How much does the service cost for a renter?
                            <i class="material-icons">keyboard_arrow_down</i>
                        </a>
                    </div>
                    <div id="collapseFour" class="collapse" role="tabpanel" aria-labelledby="headingFour">
                        <div class="card-body">
                            Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                        </div>
                    </div>
                </div>
                <div class="card card-raised p-1">
                    <div class="card-header" role="tab" id="headingFive">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                            How much does the service cost for a renter?
                            <i class="material-icons">keyboard_arrow_down</i>
                        </a>
                    </div>
                    <div id="collapseFive" class="collapse" role="tabpanel" aria-labelledby="headingFive">
                        <div class="card-body">
                            Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                        </div>
                    </div>
                </div>
                <div class="card card-raised p-1">
                    <div class="card-header" role="tab" id="headingSix">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
                            How much does the service cost for a renter?
                            <i class="material-icons">keyboard_arrow_down</i>
                        </a>
                    </div>
                    <div id="collapseSix" class="collapse" role="tabpanel" aria-labelledby="headingSix">
                        <div class="card-body">
                            Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                        </div>
                    </div>
                </div>
                <div class="card card-raised p-1">
                    <div class="card-header" role="tab" id="headingSeven">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseSeven" aria-expanded="false" aria-controls="collapseSeven">
                            How much does the service cost for a renter?
                            <i class="material-icons">keyboard_arrow_down</i>
                        </a>
                    </div>
                    <div id="collapseSeven" class="collapse" role="tabpanel" aria-labelledby="headingSeven">
                        <div class="card-body">
                            Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                        </div>
                    </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/pages/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ super }} Welcome to the Rentals App Find Your Next Dream Rental Home {% endblock %}
{% block content %}
       <div class="page-header header-filter" id="landing-page-header-img" data-parallax="true" style="background-image: url('{% static "img/houses/house-12.jpg" %}')">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1 class="title">Your Stay Starts With Us.</h1>
          <h4>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut earum fuga hic illo ipsa itaque molestiae quos rem sapiente, se</h4>
        </div>
      </div>
    </div>
  </div>
  <div class="main main-raised">
    <div class="container">
      <div class="section text-center">
        <div class="row">
          <div class="col-md-8 ml-auto mr-auto">
              {% include '_partials/_alerts.html' %}
            <h2 class="title">Let&apos;s talk product</h2>
            <h5 class="description">This is the paragraph where you can write more details about your product. Keep you user engaged by providing meaningful information. Remember that by this time, the user is curious, otherwise he wouldn&apos;t scroll to get here. Add a button if you want the user to see more.</h5>
          </div>
        </div>
        <div class="features">
          <div class="row">
            <div class="col-md-4">
              <div class="info">
                <div class="icon icon-info">
                  <i class="material-icons">chat</i>
                </div>
                <h4 class="info-title">Free Chat</h4>
                <p>Divide details about your product or agency work into parts. Write a few lines about each one. A paragraph describing a feature will be enough.</p>
              </div>
            </div>
            <div class="col-md-4">
              <div class="info">
                <div class="icon icon-success">
                  <i class="material-icons">verified_user</i>
                </div>
                <h4 class="info-title">Verified Users</h4>
                <p>Divide details about your product or agency work into parts. Write a few lines about each one. A paragraph describing a feature will be enough.</p>
              </div>
            </div>
            <div class="col-md-4">
              <div class="info">
                <div class="icon icon-danger">
                  <i class="material-icons">fingerprint</i>
                </div>
                <h4 class="info-title">Fingerprint</h4>
                <p>Divide details about your product or agency work into parts. Write a few lines about each one. A paragraph describing a feature will be enough.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="section text-center">
        <h2 class="title">Featured</h2>
             <div class="row">
                 {% if homes %}
                 {% for home in homes %}
                <div class="col-md-4">
                    <div class="rotating-card-container">
                        <div class="card card-rotate card-background">
                            <div class="front front-background" style="background-image:url('{{ home.photo_main.url }}');">
                                <div class="card-body">
                                    <h6 class="card-category">Homes Trending</h6>
                                    <a href="#pablo">
                                        <h3 class="card-title">{{ home.title }}</h3>
                                    </a>
                                    <p class="card-description">
                                        {{ home.address }} {{ home.city }}, {{ home.state }} {{ home.zipcode }}
                                    </p>
                                </div>
                            </div>

                            <div class="back back-background" style="background-image: url('{{ home.photo_main.url }}');">
                                <div class="card-body">
                                    <h5 class="card-title">
                                        {{ home.address }} {{ home.city }}, {{ home.state }} {{ home.zipcode }}
                                    </h5>
                                    <p class="card-description">
                                        <i class="fas fa-dollar-sign" style="color: forestgreen"></i> {{ home.price }} <br>
                                        <strong>Beds: </strong>{{ home.bedrooms }} <strong>Baths: </strong>{{ home.bathrooms }} <br>
                                            <strong>SQFT: </strong> {{ home.sqft }} <strong>Lot Size: </strong> {{ home.lot_size }}
                                    </p>
                                    <div class="footer justify-content-center">
                                        <a href="{% url 'properties:detail' pk=home.pk %}" class="btn btn-info btn-just-icon btn-fill btn-round">
                                            <i class="material-icons">subject</i>
                                        </a>
                                    </div>
                                </div>
                             </div>
                        </div>
                    </div>
                </div>
                 {% endfor %}
             {% endif %}
            </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/pages/privacy-policy.html
{% extends 'base.html' %}
{% block title %} {{ super }} | {% endblock %}
{% block content %}

{% endblock %}

templates/pages/terms.html
{% extends 'base.html' %}
{% block title %} {{ super }} | {% endblock %}
{% block content %}

{% endblock %}