home/urls.py
from django.urls import path

from . import views

app_name = "home"
urlpatterns = [
    path('', views.FindAHomeListView.as_view(), name='homes'),
]

owners/urls.py
from django.conf.urls import url
from . import views

app_name = "owners"
urlpatterns = [
    url('^$', views.owners, name="owners"),
    url(r'^(?P<id>\d+)/create-review/$', views.create_review, name="create_review"),
    url(r'^(?P<pk>\d+)/$', views.owner_detail, name='profile'),
]

rental_program/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('pages.urls', namespace='pages')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('home/', include('home.urls', namespace='home')),
    path('renters/', include('renters.urls', namespace='renters')),
    path('owners/', include('owners.urls', namespace='owners')),
    path('properties/', include('properties.urls', namespace='properties')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

owners/models.py
from django.db import models
from accounts.models import User


class OwnerManager(models.Manager):
    def validate_owner(self, pd):
        errors = {}
        if len(pd['name']) < 2:
            errors['name'] = 'Your name needs to be 2 or more characters.'
        elif len(pd['name']) > 100:
            errors['name'] = 'Your name cannot be more than 100 characters.'

        if len(pd['email']) > 150:
            errors['email'] = 'Your name cannot be more than 150 characters.'
        return errors


class Owner(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=150, unique=True)
    photo = models.ImageField(upload_to='photos/owners/%Y/%m/%d/', blank=True)
    description = models.TextField(default='')
    phone = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = OwnerManager()
    def __str__(self):
        return self.name


class ReviewManager(models.Manager):
    def validate_review(self, pd):
        errors = {}
        if len(pd['title']) < 2:
            errors['title'] = 'Please make your title 2 or more characters.'
        elif len(pd['title']) > 200:
            errors['title'] = 'Please make your title 200 or less characters.'
        return errors


class Review(models.Model):
    owner = models.ForeignKey(Owner, on_delete=models.DO_NOTHING)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=200)
    description = models.TextField(default='')
    stars = models.IntegerField(default=5)
    objects = ReviewManager()
    def __str__(self):
        return self.title

owners/views.py
from django.contrib import messages
from django.urls import reverse
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Owner, Review
from accounts.models import User
from properties.models import Property


def owners(request):
    owners = Owner.objects.all().order_by("name")
    context = {
        "owners": owners,
    }
    return render(request, "owners/owners.html", context)


def owner_detail(request, pk):
    owner = Owner.objects.get(id=pk)
    properties = Property.objects.filter(owner=owner).order_by('-price')[:3]
    reviews = Review.objects.filter(owner=owner).order_by('-stars')[:4]
    context = {
        "owner": owner,
        "properties": properties,
        "reviews": reviews,
    }
    return render(request, "owners/profile.html", context)


def create_review(request, id):
    if request.method == 'POST':
        username = request.user.username
        user = User.objects.get(username=username)
        owner = Owner.objects.get(id=id)
        title = request.POST['title']
        description = request.POST['description']
        stars = request.POST['stars']
        Review.objects.create(user=user, owner=owner, title=title, description=description, stars=stars)
        messages.success(request, "Review added!")
        return redirect('/owners/{}/'.format(id))
    else:
        return render(request, "owners/profile.html")

# class ReviewCreateView(CreateView):
#     fields = ("owner", "title", "description", "stars")
#     model = Review
#
#     def get_initial(self):
#         initial = super().get_initial()
#         initial['user'] = self.request.user.pk
#         return initial

templates/owners/owners.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ super }} {% endblock %}
{% block content %}
 <div class="page-header header-filter" data-parallax="true" style="background-image: url('{% static "kit/assets/img/bg5.jpg" %}');">
    <div class="container">
      <div class="row">
        <div class="col-md-8 ml-auto mr-auto text-center">
          <h1 class="title">Owners</h1>
          <h4>The Opportunities Are Endless With These Home Bearing People</h4>
        </div>
      </div>
    </div>
  </div>
    <div class="main main-raised">
        <div class="container">
            <div class="section section-text">
                <div class="row">
                    <div class="col-md-12 ml-auto mr-auto">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Photo</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Description</th>
                                    <th>Phone</th>
                                    <th>Reviews</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% if owners %}
                                {% for owner in owners %}
                                    <tr>
                                        <td><img src="{{ owner.photo.url }}" alt="{{ owner.name }}" width="230px" height="300px" class="img-fluid"></td>
                                        <td>{{ owner.name }}</td>
                                        <td>{{ owner.email }}</td>
                                        <td>{{ owner.description }}</td>
                                        <td>{{ owner.phone }}</td>
                                        <td><a href="{% url 'owners:profile' pk=owner.pk %}">{{ reviews | length }}</a></td>
                                        <td class="td-actions text-right">
                                            <div class="row">
                                                <div class="col-12 col-md-6">
                                                    <a href="{% url 'owners:profile' pk=owner.pk %}" type="button" rel="tooltip" class="btn btn-info btn-simple">
                                                        <i class="material-icons">person</i>
                                                    </a>
                                                </div>
                                                <div class="col-12 col-md-6">
                                                    <a href="#" type="button" rel="tooltip" class="btn btn-success btn-simple">
                                                        <i class="material-icons">add</i>
                                                    </a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                            {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/owners/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ super }} {{ owner.name }} {% endblock %}
{% block content %}

  <div class="page-header header-filter" data-parallax="true" style="background-image: url('{% static "kit/assets/img/bg3.jpg" %}');">
    <div class="container">
        <div class="row">
            <div class="col-md-6 ml-auto mr-auto">
                <div class="avatar" style="display: block; text-align: center;">
                <img src="{{ owner.photo.url }}" alt="{{ owner.name }}" class="img-raised rounded-circle img-fluid">
              </div>
                <h1 class="text-center"><strong>{{ owner.name }}</strong></h1>
            </div>
        </div>
    </div>
  </div>
  <div class="main main-raised">
    <div class="profile-content">
      <div class="container">
      <div class="row">
          <div class="col-md-10 ml-auto mr-auto mt-5">
              <div class="card card-nav-tabs card-raised">
    <div class="card-header">
        <!-- colors: "header-primary", "header-info", "header-success", "header-warning", "header-danger" -->
        <div class="nav-tabs-navigation">
            <div class="nav-tabs-wrapper">
                <ul class="nav nav-tabs" data-tabs="tabs">
                    <li class="nav-item" style="color:black;">
                        <a class="nav-link active" href="#about" data-toggle="tab">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#contact" data-toggle="tab">Contact Info</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#writeReview" data-toggle="tab">Write A Review</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

                  <div class="card-body ">
        <div class="tab-content text-center">
            <div class="tab-pane active" id="about">
                <h5 class="card-title">About</h5>
                <p>{{ owner.description }}</p>
                <p>I think that&#x2019;s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at. So when you get something that has the name Kanye West on it, it&#x2019;s supposed to be pushing the furthest possibilities. I will be the leader of a company that ends up being worth billions of dollars, because I got the answers. I understand culture. I am the nucleus.</p>
            </div>
            <div class="tab-pane" id="contact">
                <h5 class="card-title">Contact Information</h5>
                <p>Phone Number: {{ owner.phone }}</p>
                <p>Email Address: {{ owner.email }}</p>
            </div>
            <div class="tab-pane" id="writeReview">
                {% include '_partials/_alerts.html' %}
                <h5 class="card-title">Write A Review</h5>
                <form action="{% url 'owners:create_review' owner.id %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input class="form-control" type="text" name="title" placeholder="Enter A Title">
                    </div>
                    <div class="form-group">
                        <textarea name="description" id="description" class="form-control" cols="30" rows="10" placeholder="Enter A Description"></textarea>
                    </div>
                    <div class="form-group">
                        <select class="form-control selectpicker" data-style="btn btn-link" name="stars">
                            <option disabled>Select An Amount Of Stars</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                        </select>
                    </div>
                    <input type="submit" class="btn btn-success btn-lg btn-round" value="Write Review">
                </form>

            </div>
        </div>
    </div>
  </div>
          </div>
      </div>
      <div class="row">
          <div class="col-md-6 ml-auto mr-auto text-center mt-3">
              <h3>Homes</h3>
          </div>
      </div>
          <div class="row">
              {% if properties %}
                {% for property in properties %}
                    <div class="col-md-4">
                        <div class="rotating-card-container">
                            <div class="card card-rotate card-background">
                                <div class="front front-background" style="background-image:  url('{{ property.photo_main.url }}');">
                                    <div class="card-body">
                                        <h6 class="card-category">{{ property.title }}</h6>
                                        <a href="#">
                                            <h3 class="card-title">{{ property.address }} {{ property.city }}, {{ property.state }} {{ property.zipcode }}</h3>
                                        </a>
                                    </div>
                                </div>
                                <div class="back back-background" style="background-image: url('{{ property.photo_main.url }}');">
                                    <div class="card-body">
                                        <h5 class="card-title">House Details</h5>
                                        <p class="card-description">{{ property.description|truncatechars:100 }} <br>
                                            <i class="fas fa-dollar-sign" style="color: forestgreen"></i> {{ property.price }} <br>
                                            <strong>Beds: </strong>{{ property.bedrooms }} <strong>Baths: </strong>{{ property.bathrooms }} <br>
                                            <strong>SQFT: </strong> {{ property.sqft }} <strong>Lot Size: </strong> {{ property.lot_size }}
                                        </p>
                                        <div class="footer justify-content-center">
                                            <a href="#" class="btn btn-info btn-just-icon btn-fill btn-round">
                                                <i class="material-icons">subject</i>
                                            </a>
                                            <a href="#" class="btn btn-success btn-just-icon btn-fill btn-round btn-wd">
                                                <i class="material-icons">mode_edit</i>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
              {% endfor %}
          {% endif %}
        </div>
      <div class="row">
          <div class="col-md-6 ml-auto mr-auto text-center mt-3">
              <h3>Reviews</h3>
          </div>
      </div>
      <div class="row">
          {% for review in reviews %}
  <div class="col-md-3 ml-auto mr-auto">
    <div class="card card-pricing bg-info"><div class="card-body ">
        <div class="icon">
            <i class="material-icons">star</i>
        </div>
        <h3 class="card-title">{{ review.title }}</h3>
        {% if review.stars == 1 %}
            <p>
                <i class="material-icons">star</i>
            </p>
        {% elif review.stars == 2 %}
            <p>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
            </p>
        {% elif review.stars == 3 %}
            <p>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
            </p>
        {% elif review.stars == 4 %}
            <p>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
            </p>
        {% else %}
            <p>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
            </p>
        {% endif %}
        <p class="card-description">
            {{ review.description }}
        </p>
        </div>
    </div>
  </div>
          {% endfor %}
</div>
      </div>
    </div>
  </div>


{% endblock %}